# Generated by Django 3.1 on 2020-08-31 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Directors',
            },
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name_plural': 'Movies'},
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.director'),
            preserve_default=False,
        ),
    ]
